#
# #
# # question_136 - Loops
# # Write a for loop that iterates over the x list and prints out all the elements of the list.
#
x = [10, 12, 13, 14, 17, 19, 21, 22, 25]
for i in x:
    print(i)
#
#
# # question_137 - Loops
# # Write a for loop that iterates over the x list and prints out the remainders of each element of the list divided by 3.
#
x = [10, 12, 13, 14, 17, 19, 21, 22, 25]
for i in x:
    print(i/3)

#
# # question_138 - Loops
# # Write a for loop that iterates over the x list and prints out all the elements of the list in reversed order and multiplied by 10.
#
x = [10, 12, 13, 14, 17, 19, 21, 22, 25]
for i in sorted(x, reverse = True):
	print(i * 10)
#
#
# # question_139 - Loops
#
# # Write a for loop that iterates over the x list and prints out all the elements of the list divided by 2 and the string Great job! after the list is exhausted.
#
#
x = [10, 12, 13, 14, 17, 19, 21, 22, 25]
for i in x:
    if i / 2:
        print(x)
    else:
        print('great job!')
#
#
#
# # question_140 - Loops
#
# # Write a for loop that iterates over the x list and prints out the index of each element.

x = [10, 12, 13, 14, 17, 19, 21, 22, 25]
for i in x:
    print(x.index(i))

#
# # question_141 - Loops
#
# # Write a while loop that prints out the value of x squared while x is less than or equal to 5. Be careful not to end up with an infinite loop!
#
x = 0
while x <= 5:
    print(x ** 2)
    x = x + 1
#
# # question_142 - Loops
# # Write a while loop that prints out the value of x times 10 while x is less than or equal to 4 and then prints out Done! when x becomes larger than 4. Be careful not to end up with an infinite loop!
#
#
x = 0

while x <= 4:
    print(x * 10)
    x = x + 1
else:
    print("Done!")

#
# # question_143 - Loops
# # Write a while loop that prints out the value of x plus 10 while x is less than or equal to 15 and the remainder of x divided by 5 is 0. Be careful not to end up with an infinite loop!
x = 10
while x <= 15 and x % 5 == 0:
    print(x+10)
    x  = x+1
#
#
# # question_144 - Loops
# # Write a while loop that prints out the absolute value of x while x is negative. Be careful not to end up with an infinite loop!
x = -7
while x < 0:
    print(abs(x))
    x = x + 1


# question_145 - Loops:-
# Write a while loop that prints out the value of x times y while x is greater than or equal to 5 and less than 10, and
# prints out the result of x divided by y when x becomes 10. Be careful not to end up with an infinite loop!

#
x = 5
y = 2

while x >= 5 and x < 10:
    print(x * y)
    x = x + 1
else:
    print(x / y)
#
#
#
# # question_146 - Loops:-
# # Write code that will iterate over the x list and multiply by 10 only the elements that are greater than 20 and print them out to the screen.
#
x = [10, 12, 13, 14, 17, 19, 21, 22, 25]
for i in x:
    if i > 20:
        print(i * 20)
#
#
#
# # question_147 - Loops
#
# # Write code that will iterate over the x and y lists and multiply each element of x with each element of y, also printing the results to the screen.
x = [2, 4, 6]
y = [5, 10]

for i in x:
    for j in y:
        print(i * j)



# question_148 - Loops
# Write code that will iterate over the x and y lists and multiply each element of x with each
# element of y that is less than 12, also printing the results to the screen.
x = [2, 4, 6, 8]
y = [5, 10, 15, 20]

for i in x:
    for j in y:
        if j < 12:
            print(i * j)




# question_149  - Loops
# Write code that will iterate over the x and y lists and multiply each element of x that is greater than 5 with each
# element of y that is less than 12, also printing the results to the screen.

x = [2, 4, 6, 8]
y = [5, 10, 15, 20]

for i in x:
    for j in y:
        if i > 5 and j < 12:
            print(i * j)



# questin_150 - Loops
# Write code that will iterate over the x and y lists and multiply each element of x with each element of y that is less than or equal to 10,
# also printing the results to the screen. For y's elements that are greater than 10, multiply each element of x with y squared.

x = [2, 4, 6, 8]
y = [5, 10, 15, 20]
for i in x:
    for j in y:
        if j <= 10:
            print(i * j)
        else:
            print(i * j ** 2)



# question_151 - Loops

# Write code that will print out each character in x doubled if that character is also inside y.

x = "cryptocurrency"
y = "blockchain"
for i in x:
    for j in y:
        print(i * 2)

question_152 - Loops
Write code that will iterate over the range generated by range(9) and for each element that is between 3 and 7 inclusively
print out the result of multiplying that element by the second element in the same range.



my_range = range(9)
for i in my_range:
    if 3 <= i <= 7:
        print(i * my_range[1])


question_153 - Loops
Write code that will iterate over the range starting at 1, up to but not including 11, with a step of 2, and for
each element that is between 3 and 8 inclusively print out the result of multiplying that element by the last
element in the same range. For any other element of the range (outside [3-8]) print Outside!

for i in range(1,11,2):
    if 3 <= i <= 8:
        print(i * range(1,11,2)[-1])
    else:
        print("outside")


